name: "Afegir Pokémon"
description: "Afegeix un Pokémon a la teva Pokédex personal"
title: "[Pokédex] Afegir:"
labels: ["add-pokemon"]
body:
  - type: input
    id: nom
    attributes:
      label: Nom
      description: "Ex.: Typhlosion, Pikachu, Rapidash. (No cal posar (Hisui); ho farem amb Regió.)"
      placeholder: "Nom del Pokémon"
    validations:
      required: true

  - type: dropdown
    id: regio
    attributes:
      label: Regió
      description: "AQUÍ vol dir forma regional. Si no és una forma regional, deixa Normal."
      options:
        - "Normal"
        - "Alola"
        - "Galar"
        - "Hisui"
        - "Paldea"
    validations:
      required: true

  - type: dropdown
    id: joc
    attributes:
      label: Joc
      description: "Tria el joc on l'has capturat."
      options:
        - "Pokémon Rojo"
        - "Pokémon Verde"
        - "Pokémon Azul"
        - "Pokémon Amarillo"
        - "Pokémon Oro"
        - "Pokémon Plata"
        - "Pokémon Cristal"
        - "Pokémon Rubí"
        - "Pokémon Zafiro"
        - "Pokémon Rojo Fuego"
        - "Pokémon Verde Hoja"
        - "Pokémon Esmeralda"
        - "Pokémon Diamante"
        - "Pokémon Perla"
        - "Pokémon Platino"
        - "Pokémon Oro HeartGold"
        - "Pokémon Plata SoulSilver"
        - "Pokémon Negro"
        - "Pokémon Blanco"
        - "Pokémon Negro 2"
        - "Pokémon Blanco 2"
        - "Pokemon X"
        - "Pokémon Y"
        - "Pokémon Rubí Omega"
        - "Pokémon Zafiro Alfa"
        - "Pokémon Sol"
        - "Pokémon Luna"
        - "Pokémon Go"
        - "Pokémon Ultrasol"
        - "Pokémon Ultraluna"
        - "Pokémon: Let's Go, Pikachu!"
        - "Pokémon: Let's Go, Eevee!"
        - "Pokémon Espada"
        - "Pokémon Escudo"
        - "Pokémon Diamante Brillante"
        - "Pokémon Perla Reluciente"
        - "Leyendas Pokémon: Arceus"
        - "Pokémon Escarlata"
        - "Pokémon Púrpura"
        - "Leyendas Pokémon: Z-A"
    validations:
      required: true

  - type: dropdown
    id: naturalesa
    attributes:
      label: Naturalesa
      description: "Si no ho saps, tria “(cap)”."
      options:
        - "(cap)"
        - "Fuerte"
        - "Osada"
        - "Modesta"
        - "Serena"
        - "Miedosa"
        - "Huraña"
        - "Dócil"
        - "Afable"
        - "Amable"
        - "Activa"
        - "Firme"
        - "Agitada"
        - "Tímida"
        - "Cauta"
        - "Alegre"
        - "Pícara"
        - "Floja"
        - "Alocada"
        - "Rara"
        - "Ingenua"
        - "Audaz"
        - "Plácida"
        - "Mansa"
        - "Grosera"
        - "Seria"
    validations:
      required: true

  - type: textarea
    id: moviments
    attributes:
      label: Moviments
      description: "Un per línia o separats per coma. (Opcional)"
      placeholder: "Ex.: Lanzallamas\nInfortunio\nRapidez\nRodar"
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: "Qualsevol nota (opcional)"
      placeholder: "Ex.: evolucionat des de..."
    validations:
      required: false