name: "Afegir Pokémon"
description: "Afegeix un Pokémon a la teva Pokédex personal"
title: "[Pokédex] Afegir:"
labels: ["add-pokemon"]
body:
  - type: input
    id: nom
    attributes:
      label: Nom
      description: "Ex.: Typhlosion, Pikachu, Rapidash. (No cal posar (Hisui); ho farem amb Regió.)"
      placeholder: "Nom del Pokémon"
    validations:
      required: true

  - type: dropdown
    id: regio
    attributes:
      label: Regió
      description: "Tria la regió associada. Per formes regionals, tria Hisui/Alola/Galar/Paldea."
      options:
        - "Normal (sense forma regional)"
        - "Kanto"
        - "Johto"
        - "Hoenn"
        - "Sinnoh"
        - "Unova"
        - "Kalos"
        - "Alola"
        - "Galar"
        - "Hisui"
        - "Paldea"
    validations:
      required: true

  - type: input
    id: joc
    attributes:
      label: Joc
      description: "Ex.: Legends Arceus, Pokémon Escarlata, etc."
      placeholder: "Joc on l'has capturat"
    validations:
      required: true

  - type: input
    id: naturalesa
    attributes:
      label: Naturalesa
      description: "Ex.: Alegre, Modesta, etc. (si no ho saps, deixa-ho buit)"
      placeholder: "Naturalesa (opcional)"
    validations:
      required: false

  - type: textarea
    id: moviments
    attributes:
      label: Moviments
      description: "Un per línia o separats per coma. (Opcional)"
      placeholder: "Ex.: Lanzallamas\nInfortunio\nRapidez\nRodar"
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: "Qualsevol nota (opcional)"
      placeholder: "Ex.: evolucionat des de..."
    validations:
      required: false